theme: jekyll-theme-minimal
logo: Logo.jpg
title: Austin Lively
description: |
  He/Him/His <br>
  CS & ECE, University of Tulsa, 2022 <br>
  Oklahoma School of Science and Math, 2018

# Comment Here for testing purposes
