theme: jekyll-theme-minimal
logo: ./logo.jpg
title: Austin Lively
description: |
  He/Him/His
  CS & ECE, University of Tulsa, 2022
  Oklahoma School of Science and Math, 2018

# Comment Here for testing purposes
